name: henzstore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=!ezr+1qvg-^drqv&!x-n$!13w@yink-4*)g3xq9$m2do1z+yc2
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=o1GfrdWckD6A98EO4ouJL6zy
      - PASSAGE_API_KEY=LGyWZE4NUb.8P7eOJq8Ldg4VZETaCHulhCg0ie22Wgpa0cJuivxI2DTbrfSWhLL1MQ8mfWiGkdR
    ports:
      - 8000:8000